### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by sara-02** [gcallah/gcallah.github.io#1]
As a good open source practice, we should have a `README.md` that describes what the site is about and provide a link to it.

**Comment by gcallah** [comment]
Absolutely! Any volunteers?

**Comment by gcallah** [comment]
I'm not teaching the course this semester, but I have 288 students in 3 other courses, so right now my time is sucked up by them. But I certainly agree we need a README.md.

**Comment by sara-02** [comment]
@gcallah no problem, I can take this up :)

**Comment by sara-02** [comment]
Fixed in #2
